name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "00 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Issue marked stale due to no activity.'
        stale-pr-message: 'PR marked stale due to no activity.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
